const LOAD_ROM_IPC_EVENT = "LOAD_ROM_EVENT";
const RESTART_ROM_IPC_EVENT = "RESTART_ROM_EVENT";
const VERSION_INFO_EVENT = "VERSION_INFO_EVENT";
const CLOSE_SETTINGS_WINDOW_EVENT = "CLOSE_SETTINGS_WINDOW_EVENT";
const SETTINGS_CHANGED_EVENT = "SETTINGS_CHANGED_EVENT";

export {
    CLOSE_SETTINGS_WINDOW_EVENT,
    LOAD_ROM_IPC_EVENT,
    RESTART_ROM_IPC_EVENT,
    SETTINGS_CHANGED_EVENT,
    VERSION_INFO_EVENT
}