enum JOYPAD_BITS {
    RIGHT_ARROW_OR_A_BUTTON = 0,
    LEFT_ARROW_OR_B_BUTTON = 1,
    UP_ARROW_OR_SELECT_BUTTON = 2,
    DOWN_ARROW_OR_START_BUTTON = 3,
    CHECK_DIRECTION_ARROWS = 4,
    CHECK_BUTTONS = 5
}

export { JOYPAD_BITS };