interface IColorConstants {
  BACKGROUND_PRIMARY_COLOR: string;
  PRIMARY_COLOR: string;
  SECONDARY_COLOR: string;
  TEXT_PRIMARY: string;
  TEXT_SECONDARY: string;
  ERROR: string;
  DIVIDER_COLOR: string;
}

const LIGHT_THEME_COLORS: IColorConstants = {
  BACKGROUND_PRIMARY_COLOR: '#e0e0e0',
  PRIMARY_COLOR: '#0091ea',
  SECONDARY_COLOR: '#ffa726',
  TEXT_PRIMARY: '#222',
  TEXT_SECONDARY: '#444',
  ERROR: '#FF5F5F',
  DIVIDER_COLOR: 'rgba(0,0,0,0.12)',
};

const DARK_THEME_COLORS: IColorConstants = {
  BACKGROUND_PRIMARY_COLOR: '#121212',
  PRIMARY_COLOR: '#ffa726',
  SECONDARY_COLOR: '#267DFF',
  TEXT_PRIMARY: '#F3F3F3',
  TEXT_SECONDARY: '#DAE1E7',
  ERROR: '#FF5F5F',
  DIVIDER_COLOR: 'rgba(255,255,255,0.35)',
};

export {LIGHT_THEME_COLORS, DARK_THEME_COLORS};
