const SCANLINE_CPU_CYCLES = 456;
const OAM_MODE_CPU_CYCLES = 80;
const DMA_MODE_CPU_CYCLES = 172;
const HBLANK_CPU_CYCLES = 204;
const MAX_SCANLINES = 153;
const VBLANK_START_SCANLINE = 144;
const LCD_WIDTH = 160;
const LCD_HEIGHT = 144;
const MAX_TILES = 32;

// LCD STATUS
const LCD_BACKGROUND_ENABLE_BIT = 0;
const LCD_SPRITES_ENABLE_BIT = 1;
const LCD_BACKGROUND_TILE_MAP_BIT = 3;
const LCD_BACKGROUND_WINDOW_TILE_DATA_REGION_INDEX_BIT = 4;
const LCD_WINDOW_ENABLE_BIT = 5;
const LCD_WINDOW_TILE_MAP_BIT = 6;
const LCD_ENABLE_REGISTER_BIT = 7;

// LCD STAT
const STATE_COINCIDENCE_FLAG_BIT = 2;
const STATE_HBLANK_INTERRUPT_BIT = 3;
const STATE_VBLANK_INTERRUPT_BIT = 4;
const STATE_OAM_INTERRUPT_BIT = 5;
const STATE_COINCIDENCE_INTERRUPT_BIT = 6;

enum LCD_MODES {
    HBLANK = 0,
    VLABNK = 1,
    OAM    = 2,
    DMA    = 3
}

export {
    SCANLINE_CPU_CYCLES,
    OAM_MODE_CPU_CYCLES,
    DMA_MODE_CPU_CYCLES,
    HBLANK_CPU_CYCLES,
    LCD_ENABLE_REGISTER_BIT,
    LCD_BACKGROUND_ENABLE_BIT,
    LCD_SPRITES_ENABLE_BIT,
    LCD_WINDOW_ENABLE_BIT,
    LCD_BACKGROUND_TILE_MAP_BIT,
    LCD_BACKGROUND_WINDOW_TILE_DATA_REGION_INDEX_BIT,
    LCD_WINDOW_TILE_MAP_BIT,
    STATE_HBLANK_INTERRUPT_BIT,
    STATE_VBLANK_INTERRUPT_BIT,
    STATE_OAM_INTERRUPT_BIT,
    STATE_COINCIDENCE_FLAG_BIT,
    STATE_COINCIDENCE_INTERRUPT_BIT,
    VBLANK_START_SCANLINE,
    MAX_SCANLINES,
    LCD_HEIGHT,
    LCD_WIDTH,
    MAX_TILES,
    LCD_MODES
}