const SCANLINE_CPU_CYCLES = 456;
const OAM_MODE_CPU_CYCLES = 80;
const DMA_MODE_CPU_CYCLES = 172;
const HBLANK_CPU_CYCLES = 204
const LCD_ENABLE_REGISTER_BIT = 7;
const STATE_COINCIDENCE_FLAG_BIT = 2;
const STATE_HBLANK_INTERRUPT_BIT = 3;
const STATE_VBLANK_INTERRUPT_BIT = 4;
const STATE_OAM_INTERRUPT_BIT = 5;
const STATE_COINCIDENCE_INTERRUPT_BIT = 6;
const MAX_SCANLINES = 153;
const VBLANK_START_SCANLINE = 144;
const LCD_WIDTH = 160;
const LCD_HEIGHT = 144;

enum LCD_MODES {
    HBLANK = 0,
    VLABNK = 1,
    OAM    = 2,
    DMA    = 3
}

export {
    SCANLINE_CPU_CYCLES,
    OAM_MODE_CPU_CYCLES,
    DMA_MODE_CPU_CYCLES,
    HBLANK_CPU_CYCLES,
    LCD_ENABLE_REGISTER_BIT,
    STATE_HBLANK_INTERRUPT_BIT,
    STATE_VBLANK_INTERRUPT_BIT,
    STATE_OAM_INTERRUPT_BIT,
    STATE_COINCIDENCE_FLAG_BIT,
    STATE_COINCIDENCE_INTERRUPT_BIT,
    VBLANK_START_SCANLINE,
    MAX_SCANLINES,
    LCD_HEIGHT,
    LCD_WIDTH,
    LCD_MODES
}