import { NON_PREFIX_OP_CODES } from "./opcodes/OP_CODES_ENUM";

import NOOP_HANDLER from "./opcodes/MISCELLANEOUS/NOOP/index";
import LOAD_TO_REG_BC_A_VALUE_OF_NEXT_TWO_MEMORY_CELLS_HANDLER from "./opcodes/LOAD/LOAD_TO_REG_BC_A_VALUE_OF_NEXT_TWO_MEMORY_CELLS"
import LOAD_TO_MEMORY_CELL_FROM_BC_REGISTER_VALUE_OF_A_REGISTER_HANDLER from "./opcodes/LOAD/LOAD_TO_MEMORY_CELL_FROM_BC_REGISTER_VALUE_OF_A_REGISTER";
import INC_BC_HANDLER from "./opcodes/MATH/INC_BC";
import INC_B_HANDLER from "./opcodes/MATH/INC_B";
import DEC_B_HANDLER from "./opcodes/MATH/DEC_B";
import LOAD_TO_REG_B_VALUE_OF_NEXT_MEMORY_CELL_HANDLER from "./opcodes/LOAD/LOAD_TO_REG_B_VALUE_FROM_NEXT_MEMORY_CELL";
import RLCA_NON_PREFIX_HANDLER from "./opcodes/BITS/RLCA";
import LOAD_TO_MEMORY_CELL_COMBINED_FROM_TWO_NEXT_MEMORY_CELL_VALUE_OF_SP_REGISTER_HANDLER from "./opcodes/LOAD/LOAD_TO_MEMORY_CELL_COMBINED_FROM_TWO_NEXT_MEMORY_CELL_VALUE_OF_SP_REGISTER";
import ADD_HL_BC_HANDLER from "./opcodes/MATH/ADD_HL_BC";
import LOAD_TO_REG_A_VALUE_OF_MEMORY_CELL_FROM_BC_REGISTER_HANDLER from "./opcodes/LOAD/LOAD_TO_REG_A_VALUE_OF_MEMORY_CELL_FROM_BC_REGISTER";
import DEC_BC_HANDLER from "./opcodes/MATH/DEC_BC";
import INC_C_HANDLER from "./opcodes/MATH/INC_C";
import DEC_C_HANDLER from "./opcodes/MATH/DEC_C";
import LOAD_TO_REG_C_VALUE_OF_NEXT_MEMORY_CELL_HANDLER from "./opcodes/LOAD/LOAD_TO_REG_C_VALUE_FROM_NEXT_MEMORY_CELL";
import RRCA_NON_PREIFX_HANDLER from "./opcodes/BITS/RRCA";
import LOAD_TO_REG_DE_A_VALUE_OF_NEXT_TWO_MEMORY_CELLS_HANDLER from "./opcodes/LOAD/LOAD_TO_REG_DE_A_VALUE_OF_NEXT_TWO_MEMORY_CELLS";
import LOAD_TO_MEMORY_CELL_FROM_DE_REGISTER_VALUE_OF_A_REGISTER_HANDLER from "./opcodes/LOAD/LOAD_TO_MEMORY_CELL_FROM_DE_REGISTER_VALUE_OF_A_REGISTER";
import INC_DE_HANDLER from "./opcodes/MATH/INC_DE";
import INC_D_HANDLER from "./opcodes/MATH/INC_D";
import DEC_D_HANDLER from "./opcodes/MATH/DEC_D";
import LOAD_TO_REG_D_VALUE_OF_NEXT_MEMORY_CELL_HANDLER from "./opcodes/LOAD/LOAD_TO_REG_D_VALUE_FROM_NEXT_MEMORY_CELL";
import RLA_NON_PREFIX_HANDLER from "./opcodes/BITS/RLA";
import JMP_RELATIVE_HANDLER from "./opcodes/JMP/JMP_RELATIVE";
import ADD_HL_DE_HANDLER from "./opcodes/MATH/ADD_HL_DE";
import LOAD_TO_REG_A_VALUE_OF_MEMORY_CELL_FROM_DE_REGISTER_HANDLER from "./opcodes/LOAD/LOAD_TO_REG_A_VALUE_OF_MEMORY_CELL_FROM_DE_REGISTER";
import DEC_DE_HANDLER from "./opcodes/MATH/DEC_DE";
import INC_E_HANDLER from "./opcodes/MATH/INC_E";
import DEC_E_HANDLER from "./opcodes/MATH/DEC_E";
import LOAD_TO_REG_E_VALUE_OF_NEXT_MEMORY_CELL_HANDLER from "./opcodes/LOAD/LOAD_TO_REG_E_VALUE_FROM_NEXT_MEMORY_CELL";
import RRA_NON_PREFIX_HANDLER from "./opcodes/BITS/RRA";
import JMP_RELATIVE_IF_ZERO_FLAG_IS_NOT_SET_HANDLER from "./opcodes/JMP/JMP_RELATIVE_IF_ZERO_FLAG_IS_NOT_SET";
import LOAD_TO_REG_HL_A_VALUE_OF_NEXT_TWO_MEMORY_CELLS_HANDLER from "./opcodes/LOAD/LOAD_TO_REG_HL_A_VALUE_OF_NEXT_TWO_MEMORY_CELLS";
import LOAD_TO_MEMORY_CELL_FROM_HL_REGISTER_VALUE_OF_A_REGISTER_INCREMENT_HL_AFTER_HANDLER from "./opcodes/LOAD/LOAD_TO_MEMORY_CELL_FROM_HL_REGISTER_VALUE_OF_A_REGISTER_INCREMENT_HL_AFTER";
import INC_HL_HANDLER from "./opcodes/MATH/INC_HL";
import INC_H_HANDLER from "./opcodes/MATH/INC_H";
import DEC_H_HANDLER from "./opcodes/MATH/DEC_H";
import LOAD_TO_REG_H_VALUE_OF_NEXT_MEMORY_CELL_HANDLER from "./opcodes/LOAD/LOAD_TO_REG_H_VALUE_FROM_NEXT_MEMORY_CELL";
import DAA_HANDLER from "./opcodes/MISCELLANEOUS/DAA";
import JMP_RELATIVE_IF_ZERO_FLAG_IS_SET_HANDLER from "./opcodes/JMP/JMP_RELATIVE_IF_ZERO_FLAG_IS_SET";
import ADD_HL_HL_HANDLER from "./opcodes/MATH/ADD_HL_HL";
import LOAD_TO_REG_A_VALUE_OF_MEMORY_CELL_FROM_HL_REGISTER_INCREMENT_HL_AFTER_HANDLER from "./opcodes/LOAD/LOAD_TO_REG_A_VALUE_OF_MEMORY_CELL_FROM_HL_REGISTER_INCREMENT_HL_AFTER";
import DEC_HL_HANDLER from "./opcodes/MATH/DEC_HL";
import INC_L_HANDLER from "./opcodes/MATH/INC_L";
import DEC_L_HANDLER from "./opcodes/MATH/DEC_L";
import LOAD_TO_REG_L_VALUE_OF_NEXT_MEMORY_CELL_HANDLER from "./opcodes/LOAD/LOAD_TO_REG_L_VALUE_FROM_NEXT_MEMORY_CELL";
import CPL_HANDLER from "./opcodes/MISCELLANEOUS/CPL";
import JMP_RELATIVE_IF_CARRY_FLAG_IS_NOT_SET_HANDLER from "./opcodes/JMP/JMP_RELATIVE_IF_CARRY_FLAG_IS_NOT_SET";
import LOAD_TO_REG_SP_A_VALUE_OF_NEXT_TWO_MEMORY_CELLS_HANDLER from "./opcodes/LOAD/LOAD_TO_REG_SP_A_VALUE_OF_NEXT_TWO_MEMORY_CELLS";
import LOAD_TO_MEMORY_CELL_FROM_HL_REGISTER_VALUE_OF_A_REGISTER_DECREMENT_HL_AFTER_HANDLER from "./opcodes/LOAD/LOAD_TO_MEMORY_CELL_FROM_HL_REGISTER_VALUE_OF_A_REGISTER_DECREMENT_HL_AFTER";
import INC_SP_HANDLER from "./opcodes/MATH/INC_SP";
import INC_A_VALUE_OF_MEMORY_CELL_FROM_HL_REGISTER_HANDLER from "./opcodes/MATH/INC_A_VALUE_OF_MEMORY_CELL_FROM_HL_REGISTER";
import DEC_A_VALUE_OF_MEMORY_CELL_FROM_HL_REGISTER_HANDLER from "./opcodes/MATH/DEC_A_VALUE_OF_MEMORY_CELL_FROM_HL_REGISTER";
import LOAD_TO_MEMORY_CELL_FROM_HL_REGISTER_VALUE_OF_NEXT_MEMORY_CELL_HANDLER from "./opcodes/LOAD/LOAD_TO_MEMORY_CELL_FROM_HL_REGISTER_VALUE_OF_NEXT_MEMORY_CELL";
import SCF_HANDLER from "./opcodes/MISCELLANEOUS/SCF";
import JMP_RELATIVE_IF_CARRY_FLAG_IS_SET_HANDLER from "./opcodes/JMP/JMP_RELATIVE_IF_CARRY_FLAG_IS_SET";
import ADD_HL_SP_HANDLER from "./opcodes/MATH/ADD_HL_SP";
import LOAD_TO_REG_A_VALUE_OF_MEMORY_CELL_FROM_HL_REGISTER_DECREMENT_HL_AFTER_HANDLER from "./opcodes/LOAD/LOAD_TO_REG_A_VALUE_OF_MEMORY_CELL_FROM_HL_REGISTER_DECREMENT_HL_AFTER";
import DEC_SP_HANDLER from "./opcodes/MATH/DEC_SP";
import INC_A_HANDLER from "./opcodes/MATH/INC_A";
import DEC_A_HANDLER from "./opcodes/MATH/DEC_A";
import LOAD_TO_REG_A_VALUE_OF_NEXT_MEMORY_CELL_HANDLER from "./opcodes/LOAD/LOAD_TO_REG_A_VALUE_FROM_NEXT_MEMORY_CELL";
import CCF_HANDLER from "./opcodes/MISCELLANEOUS/CCF";
import LOAD_TO_REG_B_VALUE_OF_REG_B_HANDLER from "./opcodes/LOAD/LOAD_TO_REG_B_VALUE_OF_REG_B";
import LOAD_TO_REG_B_VALUE_OF_REG_C_HANDLER from "./opcodes/LOAD/LOAD_TO_REG_B_VALUE_OF_REG_C";
import LOAD_TO_REG_B_VALUE_OF_REG_D_HANDLER from "./opcodes/LOAD/LOAD_TO_REG_B_VALUE_OF_REG_D";
import LOAD_TO_REG_B_VALUE_OF_REG_E_HANDLER from "./opcodes/LOAD/LOAD_TO_REG_B_VALUE_OF_REG_E";
import LOAD_TO_REG_B_VALUE_OF_REG_H_HANDLER from "./opcodes/LOAD/LOAD_TO_REG_B_VALUE_OF_REG_H";
import LOAD_TO_REG_B_VALUE_OF_REG_L_HANDLER from "./opcodes/LOAD/LOAD_TO_REG_B_VALUE_OF_REG_L";
import LOAD_TO_REG_B_VALUE_OF_MEMORY_CELL_FROM_HL_REGISTER_HANDLER from "./opcodes/LOAD/LOAD_TO_REG_B_VALUE_OF_MEMORY_CELL_FROM_HL_REGISTER";
import LOAD_TO_REG_B_VALUE_OF_REG_A_HANDLER from "./opcodes/LOAD/LOAD_TO_REG_B_VALUE_OF_REG_A";
import LOAD_TO_REG_C_VALUE_OF_REG_B_HANDLER from "./opcodes/LOAD/LOAD_TO_REG_C_VALUE_OF_REG_B";
import LOAD_TO_REG_C_VALUE_OF_REG_C_HANDLER from "./opcodes/LOAD/LOAD_TO_REG_C_VALUE_OF_REG_C";
import LOAD_TO_REG_C_VALUE_OF_REG_D_HANDLER from "./opcodes/LOAD/LOAD_TO_REG_C_VALUE_OF_REG_D";
import LOAD_TO_REG_C_VALUE_OF_REG_E_HANDLER from "./opcodes/LOAD/LOAD_TO_REG_C_VALUE_OF_REG_E";
import LOAD_TO_REG_C_VALUE_OF_REG_H_HANDLER from "./opcodes/LOAD/LOAD_TO_REG_C_VALUE_OF_REG_H";
import LOAD_TO_REG_C_VALUE_OF_REG_L_HANDLER from "./opcodes/LOAD/LOAD_TO_REG_C_VALUE_OF_REG_L";
import LOAD_TO_REG_C_VALUE_OF_MEMORY_CELL_FROM_HL_REGISTER_HANDLER from "./opcodes/LOAD/LOAD_TO_REG_C_VALUE_OF_MEMORY_CELL_FROM_HL_REGISTER";
import LOAD_TO_REG_C_VALUE_OF_REG_A_HANDLER from "./opcodes/LOAD/LOAD_TO_REG_C_VALUE_OF_REG_A";
import LOAD_TO_REG_D_VALUE_OF_REG_B_HANDLER from "./opcodes/LOAD/LOAD_TO_REG_D_VALUE_OF_REG_B";
import LOAD_TO_REG_D_VALUE_OF_REG_C_HANDLER from "./opcodes/LOAD/LOAD_TO_REG_D_VALUE_OF_REG_C";
import LOAD_TO_REG_D_VALUE_OF_REG_D_HANDLER from "./opcodes/LOAD/LOAD_TO_REG_D_VALUE_OF_REG_D";
import LOAD_TO_REG_D_VALUE_OF_REG_E_HANDLER from "./opcodes/LOAD/LOAD_TO_REG_D_VALUE_OF_REG_E";
import LOAD_TO_REG_D_VALUE_OF_REG_H_HANDLER from "./opcodes/LOAD/LOAD_TO_REG_D_VALUE_OF_REG_H";
import LOAD_TO_REG_D_VALUE_OF_REG_L_HANDLER from "./opcodes/LOAD/LOAD_TO_REG_D_VALUE_OF_REG_L";
import LOAD_TO_REG_D_VALUE_OF_MEMORY_CELL_FROM_HL_REGISTER_HANDLER from "./opcodes/LOAD/LOAD_TO_REG_D_VALUE_OF_MEMORY_CELL_FROM_HL_REGISTER";
import LOAD_TO_REG_D_VALUE_OF_REG_A_HANDLER from "./opcodes/LOAD/LOAD_TO_REG_D_VALUE_OF_REG_A";
import LOAD_TO_REG_E_VALUE_OF_REG_B_HANDLER from "./opcodes/LOAD/LOAD_TO_REG_E_VALUE_OF_REG_B";
import LOAD_TO_REG_E_VALUE_OF_REG_C_HANDLER from "./opcodes/LOAD/LOAD_TO_REG_E_VALUE_OF_REG_C";
import LOAD_TO_REG_E_VALUE_OF_REG_D_HANDLER from "./opcodes/LOAD/LOAD_TO_REG_E_VALUE_OF_REG_D";
import LOAD_TO_REG_E_VALUE_OF_REG_E_HANDLER from "./opcodes/LOAD/LOAD_TO_REG_E_VALUE_OF_REG_E";
import LOAD_TO_REG_E_VALUE_OF_REG_H_HANDLER from "./opcodes/LOAD/LOAD_TO_REG_E_VALUE_OF_REG_H";
import LOAD_TO_REG_E_VALUE_OF_REG_L_HANDLER from "./opcodes/LOAD/LOAD_TO_REG_E_VALUE_OF_REG_L";
import LOAD_TO_REG_E_VALUE_OF_MEMORY_CELL_FROM_HL_REGISTER_HANDLER from "./opcodes/LOAD/LOAD_TO_REG_E_VALUE_OF_MEMORY_CELL_FROM_HL_REGISTER";
import LOAD_TO_REG_E_VALUE_OF_REG_A_HANDLER from "./opcodes/LOAD/LOAD_TO_REG_E_VALUE_OF_REG_A";
import LOAD_TO_REG_H_VALUE_OF_REG_B_HANDLER from "./opcodes/LOAD/LOAD_TO_REG_H_VALUE_OF_REG_B";
import LOAD_TO_REG_H_VALUE_OF_REG_C_HANDLER from "./opcodes/LOAD/LOAD_TO_REG_H_VALUE_OF_REG_C";
import LOAD_TO_REG_H_VALUE_OF_REG_D_HANDLER from "./opcodes/LOAD/LOAD_TO_REG_H_VALUE_OF_REG_D";
import LOAD_TO_REG_H_VALUE_OF_REG_E_HANDLER from "./opcodes/LOAD/LOAD_TO_REG_H_VALUE_OF_REG_E";
import LOAD_TO_REG_H_VALUE_OF_REG_H_HANDLER from "./opcodes/LOAD/LOAD_TO_REG_H_VALUE_OF_REG_H";
import LOAD_TO_REG_H_VALUE_OF_REG_L_HANDLER from "./opcodes/LOAD/LOAD_TO_REG_H_VALUE_OF_REG_L";
import LOAD_TO_REG_H_VALUE_OF_MEMORY_CELL_FROM_HL_REGISTER_HANDLER from "./opcodes/LOAD/LOAD_TO_REG_H_VALUE_OF_MEMORY_CELL_FROM_HL_REGISTER";
import LOAD_TO_REG_H_VALUE_OF_REG_A_HANDLER from "./opcodes/LOAD/LOAD_TO_REG_H_VALUE_OF_REG_A";
import LOAD_TO_REG_L_VALUE_OF_REG_B_HANDLER from "./opcodes/LOAD/LOAD_TO_REG_L_VALUE_OF_REG_B";
import LOAD_TO_REG_L_VALUE_OF_REG_C_HANDLER from "./opcodes/LOAD/LOAD_TO_REG_L_VALUE_OF_REG_C";
import LOAD_TO_REG_L_VALUE_OF_REG_D_HANDLER from "./opcodes/LOAD/LOAD_TO_REG_L_VALUE_OF_REG_D";
import LOAD_TO_REG_L_VALUE_OF_REG_E_HANDLER from "./opcodes/LOAD/LOAD_TO_REG_L_VALUE_OF_REG_E";
import LOAD_TO_REG_L_VALUE_OF_REG_H_HANDLER from "./opcodes/LOAD/LOAD_TO_REG_L_VALUE_OF_REG_H";
import LOAD_TO_REG_L_VALUE_OF_REG_L_HANDLER from "./opcodes/LOAD/LOAD_TO_REG_L_VALUE_OF_REG_L";
import LOAD_TO_REG_L_VALUE_OF_MEMORY_CELL_FROM_HL_REGISTER_HANDLER from "./opcodes/LOAD/LOAD_TO_REG_L_VALUE_OF_MEMORY_CELL_FROM_HL_REGISTER";
import LOAD_TO_REG_L_VALUE_OF_REG_A_HANDLER from "./opcodes/LOAD/LOAD_TO_REG_L_VALUE_OF_REG_A";
import LOAD_TO_MEMORY_CELL_FROM_HL_REGISTER_VALUE_OF_B_REGISTER_HANDLER from "./opcodes/LOAD/LOAD_TO_MEMORY_CELL_FROM_HL_REGISTER_VALUE_OF_B_REGISTER";
import LOAD_TO_MEMORY_CELL_FROM_HL_REGISTER_VALUE_OF_C_REGISTER_HANDLER from "./opcodes/LOAD/LOAD_TO_MEMORY_CELL_FROM_HL_REGISTER_VALUE_OF_C_REGISTER";
import LOAD_TO_MEMORY_CELL_FROM_HL_REGISTER_VALUE_OF_D_REGISTER_HANDLER from "./opcodes/LOAD/LOAD_TO_MEMORY_CELL_FROM_HL_REGISTER_VALUE_OF_D_REGISTER";
import LOAD_TO_MEMORY_CELL_FROM_HL_REGISTER_VALUE_OF_E_REGISTER_HANDLER from "./opcodes/LOAD/LOAD_TO_MEMORY_CELL_FROM_HL_REGISTER_VALUE_OF_E_REGISTER";
import LOAD_TO_MEMORY_CELL_FROM_HL_REGISTER_VALUE_OF_H_REGISTER_HANDLER from "./opcodes/LOAD/LOAD_TO_MEMORY_CELL_FROM_HL_REGISTER_VALUE_OF_H_REGISTER";
import LOAD_TO_MEMORY_CELL_FROM_HL_REGISTER_VALUE_OF_L_REGISTER_HANDLER from "./opcodes/LOAD/LOAD_TO_MEMORY_CELL_FROM_HL_REGISTER_VALUE_OF_L_REGISTER";
import LOAD_TO_MEMORY_CELL_FROM_HL_REGISTER_VALUE_OF_A_REGISTER_HANDLER from "./opcodes/LOAD/LOAD_TO_MEMORY_CELL_FROM_HL_REGISTER_VALUE_OF_A_REGISTER";
import LOAD_TO_REG_A_VALUE_OF_REG_B_HANDLER from "./opcodes/LOAD/LOAD_TO_REG_A_VALUE_OF_REG_B";
import LOAD_TO_REG_A_VALUE_OF_REG_C_HANDLER from "./opcodes/LOAD/LOAD_TO_REG_A_VALUE_OF_REG_C";
import LOAD_TO_REG_A_VALUE_OF_REG_D_HANDLER from "./opcodes/LOAD/LOAD_TO_REG_A_VALUE_OF_REG_D";
import LOAD_TO_REG_A_VALUE_OF_REG_E_HANDLER from "./opcodes/LOAD/LOAD_TO_REG_A_VALUE_OF_REG_E";
import LOAD_TO_REG_A_VALUE_OF_REG_H_HANDLER from "./opcodes/LOAD/LOAD_TO_REG_A_VALUE_OF_REG_H";
import LOAD_TO_REG_A_VALUE_OF_REG_L_HANDLER from "./opcodes/LOAD/LOAD_TO_REG_A_VALUE_OF_REG_L";
import LOAD_TO_REG_A_VALUE_OF_MEMORY_CELL_FROM_HL_REGISTER_HANDLER from "./opcodes/LOAD/LOAD_TO_REG_A_VALUE_OF_MEMORY_CELL_FROM_HL_REGISTER";
import LOAD_TO_REG_A_VALUE_OF_REG_A_HANDLER from "./opcodes/LOAD/LOAD_TO_REG_A_VALUE_OF_REG_A";
import ADD_TO_REG_A_VALUE_OF_REG_B_HANDLER from "./opcodes/MATH/ADD_TO_REG_A_VALUE_OF_REG_B";
import ADD_TO_REG_A_VALUE_OF_REG_C_HANDLER from "./opcodes/MATH/ADD_TO_REG_A_VALUE_OF_REG_C";
import ADD_TO_REG_A_VALUE_OF_REG_D_HANDLER from "./opcodes/MATH/ADD_TO_REG_A_VALUE_OF_REG_D";
import ADD_TO_REG_A_VALUE_OF_REG_E_HANDLER from "./opcodes/MATH/ADD_TO_REG_A_VALUE_OF_REG_E";
import ADD_TO_REG_A_VALUE_OF_REG_H_HANDLER from "./opcodes/MATH/ADD_TO_REG_A_VALUE_OF_REG_H";
import ADD_TO_REG_A_VALUE_OF_REG_L_HANDLER from "./opcodes/MATH/ADD_TO_REG_A_VALUE_OF_REG_L";
import ADD_TO_REG_A_VALUE_OF_MEMORY_CELL_FROM_HL_REGISTER_HANDLER from "./opcodes/MATH/ADD_TO_REG_A_VALUE_OF_MEMORY_CELL_FROM_HL_REGISTER";
import ADD_TO_REG_A_VALUE_OF_REG_A_HANDLER from "./opcodes/MATH/ADD_TO_REG_A_VALUE_OF_REG_A";
import ADC_TO_REG_A_VALUE_OF_REG_B_HANDLER from "./opcodes/MATH/ADC_TO_REG_A_VALUE_OF_REG_B";
import ADC_TO_REG_A_VALUE_OF_REG_C_HANDLER from "./opcodes/MATH/ADC_TO_REG_A_VALUE_OF_REG_C";
import ADC_TO_REG_A_VALUE_OF_REG_D_HANDLER from "./opcodes/MATH/ADC_TO_REG_A_VALUE_OF_REG_D";
import ADC_TO_REG_A_VALUE_OF_REG_E_HANDLER from "./opcodes/MATH/ADC_TO_REG_A_VALUE_OF_REG_E";
import ADC_TO_REG_A_VALUE_OF_REG_H_HANDLER from "./opcodes/MATH/ADC_TO_REG_A_VALUE_OF_REG_H";
import ADC_TO_REG_A_VALUE_OF_REG_L_HANDLER from "./opcodes/MATH/ADC_TO_REG_A_VALUE_OF_REG_L";
import ADC_TO_REG_A_VALUE_OF_MEMORY_CELL_FROM_HL_REGISTER_HANDLER from "./opcodes/MATH/ADC_TO_REG_A_VALUE_OF_MEMORY_CELL_FROM_HL_REGISTER";
import ADC_TO_REG_A_VALUE_OF_REG_A_HANDLER from "./opcodes/MATH/ADC_TO_REG_A_VALUE_OF_REG_A";
import SUB_FROM_REG_A_VALUE_OF_REG_B_HANDLER from "./opcodes/MATH/SUB_FROM_REG_A_VALUE_OF_REG_B";
import SUB_FROM_REG_A_VALUE_OF_REG_C_HANDLER from "./opcodes/MATH/SUB_FROM_REG_A_VALUE_OF_REG_C";
import SUB_FROM_REG_A_VALUE_OF_REG_D_HANDLER from "./opcodes/MATH/SUB_FROM_REG_A_VALUE_OF_REG_D";
import SUB_FROM_REG_A_VALUE_OF_REG_E_HANDLER from "./opcodes/MATH/SUB_FROM_REG_A_VALUE_OF_REG_E";
import SUB_FROM_REG_A_VALUE_OF_REG_H_HANDLER from "./opcodes/MATH/SUB_FROM_REG_A_VALUE_OF_REG_H";
import SUB_FROM_REG_A_VALUE_OF_REG_L_HANDLER from "./opcodes/MATH/SUB_FROM_REG_A_VALUE_OF_REG_L";
import SUB_FROM_REG_A_VALUE_OF_MEMORY_CELL_FROM_HL_REGISTER_HANDLER from "./opcodes/MATH/SUB_FROM_REG_A_VALUE_OF_MEMORY_CELL_FROM_HL_REGISTER";
import SUB_FROM_REG_A_VALUE_OF_REG_A_HANDLER from "./opcodes/MATH/SUB_FROM_REG_A_VALUE_OF_REG_A";
import SBC_FROM_REG_A_VALUE_OF_REG_B_HANDLER from "./opcodes/MATH/SBC_FROM_REG_A_VALUE_OF_REG_B";
import SBC_FROM_REG_A_VALUE_OF_REG_C_HANDLER from "./opcodes/MATH/SBC_FROM_REG_A_VALUE_OF_REG_C";
import SBC_FROM_REG_A_VALUE_OF_REG_D_HANDLER from "./opcodes/MATH/SBC_FROM_REG_A_VALUE_OF_REG_D";
import SBC_FROM_REG_A_VALUE_OF_REG_E_HANDLER from "./opcodes/MATH/SBC_FROM_REG_A_VALUE_OF_REG_E";
import SBC_FROM_REG_A_VALUE_OF_REG_H_HANDLER from "./opcodes/MATH/SBC_FROM_REG_A_VALUE_OF_REG_H";
import SBC_FROM_REG_A_VALUE_OF_REG_L_HANDLER from "./opcodes/MATH/SBC_FROM_REG_A_VALUE_OF_REG_L";
import SBC_FROM_REG_A_VALUE_OF_MEMORY_CELL_FROM_HL_REGISTER_HANDLER from "./opcodes/MATH/SBC_FROM_REG_A_VALUE_OF_MEMORY_CELL_FROM_HL_REGISTER";
import SBC_FROM_REG_A_VALUE_OF_REG_A_HANDLER from "./opcodes/MATH/SBC_FROM_REG_A_VALUE_OF_REG_A";
import AND_B_HANDLER from "./opcodes/BOOLEAN/AND_B";
import AND_C_HANDLER from "./opcodes/BOOLEAN/AND_C";
import AND_D_HANDLER from "./opcodes/BOOLEAN/AND_D";
import AND_E_HANDLER from "./opcodes/BOOLEAN/AND_E";
import AND_H_HANDLER from "./opcodes/BOOLEAN/AND_H";
import AND_L_HANDLER from "./opcodes/BOOLEAN/AND_L";
import AND_A_VALUE_OF_MEMORY_CELL_FROM_HL_REGISTER_HANDLER from "./opcodes/BOOLEAN/AND_A_VALUE_OF_MEMORY_CELL_FROM_HL_REGISTER";
import AND_A_HANDLER from "./opcodes/BOOLEAN/AND_A";
import XOR_B_HANDLER from "./opcodes/BOOLEAN/XOR_B";
import XOR_C_HANDLER from "./opcodes/BOOLEAN/XOR_C";
import XOR_D_HANDLER from "./opcodes/BOOLEAN/XOR_D";
import XOR_E_HANDLER from "./opcodes/BOOLEAN/XOR_E";
import XOR_H_HANDLER from "./opcodes/BOOLEAN/XOR_H";
import XOR_L_HANDLER from "./opcodes/BOOLEAN/XOR_L";
import XOR_A_VALUE_OF_MEMORY_CELL_FROM_HL_REGISTER_HANDLER from "./opcodes/BOOLEAN/XOR_A_VALUE_OF_MEMORY_CELL_FROM_HL_REGISTER";
import XOR_A_HANDLER from "./opcodes/BOOLEAN/XOR_A";
import OR_B_HANDLER from "./opcodes/BOOLEAN/OR_B";
import OR_C_HANDLER from "./opcodes/BOOLEAN/OR_C";
import OR_D_HANDLER from "./opcodes/BOOLEAN/OR_D";
import OR_E_HANDLER from "./opcodes/BOOLEAN/OR_E";
import OR_H_HANDLER from "./opcodes/BOOLEAN/OR_H";
import OR_L_HANDLER from "./opcodes/BOOLEAN/OR_L";
import OR_A_VALUE_OF_MEMORY_CELL_FROM_HL_REGISTER_HANDLER from "./opcodes/BOOLEAN/OR_A_VALUE_OF_MEMORY_CELL_FROM_HL_REGISTER";
import OR_A_HANDLER from "./opcodes/BOOLEAN/OR_A";
import CP_B_HANDLER from "./opcodes/BOOLEAN/CP_B";
import CP_C_HANDLER from "./opcodes/BOOLEAN/CP_C";
import CP_D_HANDLER from "./opcodes/BOOLEAN/CP_D";
import CP_E_HANDLER from "./opcodes/BOOLEAN/CP_E";
import CP_H_HANDLER from "./opcodes/BOOLEAN/CP_H";
import CP_L_HANDLER from "./opcodes/BOOLEAN/CP_L";
import CP_A_VALUE_OF_MEMORY_CELL_FROM_HL_REGISTER_HANDLER from "./opcodes/BOOLEAN/CP_A_VALUE_OF_MEMORY_CELL_FROM_HL_REGISTER";
import CP_A_HANDLER from "./opcodes/BOOLEAN/CP_A";
import RETURN_IF_ZERO_FLAG_IS_NOT_SET_HANDLER from "./opcodes/STACK/RETURN_IF_ZERO_FLAG_IS_NOT_SET";
import POP_BC_HANDLER from "./opcodes/STACK/POP_BC";
import JMP_IF_ZERO_FLAG_IS_NOT_SET_HANDLER from "./opcodes/JMP/JMP_IF_ZERO_FLAG_IS_NOT_SET";
import JMP_HANDLER from "./opcodes/JMP/JMP";
import CALL_IF_ZERO_FLAG_IS_NOT_SET_HANDLER from "./opcodes/STACK/CALL_IF_ZERO_FLAG_IS_NOT_SET";
import PUSH_BC_HANDLER from "./opcodes/STACK/PUSH_BC";
import ADD_TO_REG_A_VALUE_FROM_NEXT_MEMORY_CELL_HANDLER from "./opcodes/MATH/ADD_TO_REG_A_VALUE_FROM_NEXT_MEMORY_CELL";
import RST_0_HANDLER from "./opcodes/STACK/RST_0";
import RETURN_IF_ZERO_FLAG_IS_SET_HANDLER from "./opcodes/STACK/RETURN_IF_ZERO_FLAG_IS_SET";
import RETURN_HANDLER from "./opcodes/STACK/RETURN";
import JMP_IF_ZERO_FLAG_IS_SET_HANDLER from "./opcodes/JMP/JMP_IF_ZERO_FLAG_IS_SET";
import CALL_IF_ZERO_FLAG_IS_SET_HANDLER from "./opcodes/STACK/CALL_IF_ZERO_FLAG_IS_SET";
import CALL_HANDLER from "./opcodes/STACK/CALL";
import ADC_TO_REG_A_VALUE_FROM_NEXT_MEMORY_CELL_HANDLER from "./opcodes/MATH/ADC_TO_REG_A_VALUE_FROM_NEXT_MEMORY_CELL";
import RST_08_HANDLER from "./opcodes/STACK/RST_08";
import RETURN_IF_CARRY_FLAG_IS_NOT_SET_HANDLER from "./opcodes/STACK/RETURN_IF_CARRY_FLAG_IS_NOT_SET";
import POP_DE_HANDLER from "./opcodes/STACK/POP_DE";
import JMP_IF_CARRY_FLAG_IS_NOT_SET_HANDLER from "./opcodes/JMP/JMP_IF_CARRY_FLAG_IS_NOT_SET";
import CALL_IF_CARRY_FLAG_IS_NOT_SET_HANDLER from "./opcodes/STACK/CALL_IF_CARRY_FLAG_IS_NOT_SET";
import PUSH_DE_HANDLER from "./opcodes/STACK/PUSH_DE";
import SUB_FROM_REG_A_VALUE_FROM_NEXT_MEMORY_CELL_HANDLER from "./opcodes/MATH/SUB_FROM_REG_A_VALUE_FROM_NEXT_MEMORY_CELL";
import RST_10_HANDLER from "./opcodes/STACK/RST_10";
import RETURN_IF_CARRY_FLAG_IS_SET_HANDLER from "./opcodes/STACK/RETURN_IF_CARRY_FLAG_IS_SET";
import RETURN_AND_ENABLE_INTERRUPTS_HANDLER from "./opcodes/STACK/RETURN_AND_ENABLE_INTERRUPTS";
import JMP_IF_CARRY_FLAG_IS_SET_HANDLER from "./opcodes/JMP/JMP_IF_CARRY_FLAG_IS_SET";
import CALL_IF_CARRY_IS_SET_HANDLER from "./opcodes/STACK/CALL_IF_CARRY_FLAG_IS_SET";
import SBC_FROM_REG_A_VALUE_FROM_NEXT_MEMORY_CELL_HANDLER from "./opcodes/MATH/SBC_FROM_REG_A_VALUE_FROM_NEXT_MEMORY_CELL";
import RST_18_HANDLER from "./opcodes/STACK/RST_18";
import LOAD_HIGH_TO_MEMORY_CELL_COMBINED_FROM_NEXT_MEMORY_CELL_VALUE_OF_A_REGISTER_HANDLER from "./opcodes/LOAD/LOAD_HIGH_TO_MEMORY_CELL_COMBINED_FROM_NEXT_MEMORY_CELL_VALUE_OF_A_REGISTER";
import POP_HL_HANDLER from "./opcodes/STACK/POP_HL";
import LOAD_TO_MEMORY_CELL_FROM_C_REGISTER_VALUE_OF_A_REGISTER_HANDLER from "./opcodes/LOAD/LOAD_TO_MEMORY_CELL_FROM_C_REGISTER_VALUE_OF_A_REGISTER";
import PUSH_HL_HANDLER from "./opcodes/STACK/PUSH_HL";
import AND_A_VALUE_FROM_NEXT_MEMORY_CELL_HANDLER from "./opcodes/BOOLEAN/AND_A_VALUE_FROM_NEXT_MEMORY_CELL";
import RST_20_HANDLER from "./opcodes/STACK/RST_20";
import ADD_TO_SP_A_VALUE_FROM_NEXT_MEMORY_CELL_HANDLER from "./opcodes/MATH/ADD_TO_SP_A_VALUE_FROM_NEXT_MEMORY_CELL";
import JMP_TO_HL_HANDLER from "./opcodes/JMP/JMP_HL";
import LOAD_TO_MEMORY_CELL_COMBINED_FROM_TWO_NEXT_MEMORY_CELL_VALUE_OF_A_REGISTER_HANDLER from "./opcodes/LOAD/LOAD_TO_MEMORY_CELL_COMBINED_FROM_TWO_NEXT_MEMORY_CELL_VALUE_OF_A_REGISTER";
import XOR_A_VALUE_FROM_NEXT_MEMORY_CELL_HANDLER from "./opcodes/BOOLEAN/XOR_A_VALUE_FROM_NEXT_MEMORY_CELL";
import RST_28_HANDLER from "./opcodes/STACK/RST_28";

import { IJumpTable } from "./types";

const JUMP_TABLE: IJumpTable = {
    [NON_PREFIX_OP_CODES.NOOP]: NOOP_HANDLER,
    [NON_PREFIX_OP_CODES.LOAD_TO_REG_BC_A_VALUE_OF_NEXT_TWO_MEMORY_CELLS]:  LOAD_TO_REG_BC_A_VALUE_OF_NEXT_TWO_MEMORY_CELLS_HANDLER,
    [NON_PREFIX_OP_CODES.LOAD_TO_MEMORY_CELL_FROM_BC_REGISTER_VALUE_OF_A_REGISTER]: LOAD_TO_MEMORY_CELL_FROM_BC_REGISTER_VALUE_OF_A_REGISTER_HANDLER,
    [NON_PREFIX_OP_CODES.INC_BC]: INC_BC_HANDLER,
    [NON_PREFIX_OP_CODES.INC_B]: INC_B_HANDLER,
    [NON_PREFIX_OP_CODES.DEC_B]: DEC_B_HANDLER,
    [NON_PREFIX_OP_CODES.LOAD_TO_REG_B_VALUE_OF_NEXT_MEMORY_CELL]: LOAD_TO_REG_B_VALUE_OF_NEXT_MEMORY_CELL_HANDLER,
    [NON_PREFIX_OP_CODES.RLCA]: RLCA_NON_PREFIX_HANDLER,
    [NON_PREFIX_OP_CODES.LOAD_TO_MEMORY_CELL_COMBINED_FROM_TWO_NEXT_MEMORY_CELL_VALUE_OF_SP_REGISTER]: LOAD_TO_MEMORY_CELL_COMBINED_FROM_TWO_NEXT_MEMORY_CELL_VALUE_OF_SP_REGISTER_HANDLER,
    [NON_PREFIX_OP_CODES.ADD_HL_BC]: ADD_HL_BC_HANDLER,
    [NON_PREFIX_OP_CODES.LOAD_TO_REG_A_VALUE_OF_MEMORY_CELL_FROM_BC_REGISTER]: LOAD_TO_REG_A_VALUE_OF_MEMORY_CELL_FROM_BC_REGISTER_HANDLER,
    [NON_PREFIX_OP_CODES.DEC_BC]: DEC_BC_HANDLER,
    [NON_PREFIX_OP_CODES.INC_C]: INC_C_HANDLER,
    [NON_PREFIX_OP_CODES.DEC_C]: DEC_C_HANDLER,
    [NON_PREFIX_OP_CODES.LOAD_TO_REG_C_VALUE_OF_NEXT_MEMORY_CELL]: LOAD_TO_REG_C_VALUE_OF_NEXT_MEMORY_CELL_HANDLER,
    [NON_PREFIX_OP_CODES.RRCA]: RRCA_NON_PREIFX_HANDLER,
    [NON_PREFIX_OP_CODES.LOAD_TO_REG_DE_A_VALUE_OF_NEXT_TWO_MEMORY_CELLS]: LOAD_TO_REG_DE_A_VALUE_OF_NEXT_TWO_MEMORY_CELLS_HANDLER,
    [NON_PREFIX_OP_CODES.LOAD_TO_MEMORY_CELL_FROM_DE_REGISTER_VALUE_OF_A_REGISTER]: LOAD_TO_MEMORY_CELL_FROM_DE_REGISTER_VALUE_OF_A_REGISTER_HANDLER,
    [NON_PREFIX_OP_CODES.INC_DE]: INC_DE_HANDLER,
    [NON_PREFIX_OP_CODES.INC_D]: INC_D_HANDLER,
    [NON_PREFIX_OP_CODES.DEC_D]: DEC_D_HANDLER,
    [NON_PREFIX_OP_CODES.LOAD_TO_REG_D_VALUE_OF_NEXT_MEMORY_CELL]: LOAD_TO_REG_D_VALUE_OF_NEXT_MEMORY_CELL_HANDLER,
    [NON_PREFIX_OP_CODES.RLA]: RLA_NON_PREFIX_HANDLER,
    [NON_PREFIX_OP_CODES.JMP_RELATIVE]: JMP_RELATIVE_HANDLER,
    [NON_PREFIX_OP_CODES.ADD_HL_DE]: ADD_HL_DE_HANDLER,
    [NON_PREFIX_OP_CODES.LOAD_TO_REG_A_VALUE_OF_MEMORY_CELL_FROM_DE_REGISTER]: LOAD_TO_REG_A_VALUE_OF_MEMORY_CELL_FROM_DE_REGISTER_HANDLER,
    [NON_PREFIX_OP_CODES.DEC_DE]: DEC_DE_HANDLER,
    [NON_PREFIX_OP_CODES.INC_E]: INC_E_HANDLER,
    [NON_PREFIX_OP_CODES.DEC_E]: DEC_E_HANDLER,
    [NON_PREFIX_OP_CODES.LOAD_TO_REG_E_VALUE_OF_NEXT_MEMORY_CELL]: LOAD_TO_REG_E_VALUE_OF_NEXT_MEMORY_CELL_HANDLER,
    [NON_PREFIX_OP_CODES.RRA]: RRA_NON_PREFIX_HANDLER,
    [NON_PREFIX_OP_CODES.JMP_RELATIVE_IF_ZERO_FLAG_IS_NOT_SET]: JMP_RELATIVE_IF_ZERO_FLAG_IS_NOT_SET_HANDLER,
    [NON_PREFIX_OP_CODES.LOAD_TO_REG_HL_A_VALUE_OF_NEXT_TWO_MEMORY_CELLS]: LOAD_TO_REG_HL_A_VALUE_OF_NEXT_TWO_MEMORY_CELLS_HANDLER,
    [NON_PREFIX_OP_CODES.LOAD_TO_MEMORY_CELL_FROM_HL_REGISTER_VALUE_OF_A_REGISTER_INCREMENT_HL_AFTER]: LOAD_TO_MEMORY_CELL_FROM_HL_REGISTER_VALUE_OF_A_REGISTER_INCREMENT_HL_AFTER_HANDLER,
    [NON_PREFIX_OP_CODES.INC_HL]: INC_HL_HANDLER,
    [NON_PREFIX_OP_CODES.INC_H]: INC_H_HANDLER,
    [NON_PREFIX_OP_CODES.DEC_H]: DEC_H_HANDLER,
    [NON_PREFIX_OP_CODES.LOAD_TO_REG_H_VALUE_OF_NEXT_MEMORY_CELL]: LOAD_TO_REG_H_VALUE_OF_NEXT_MEMORY_CELL_HANDLER,
    [NON_PREFIX_OP_CODES.DAA]: DAA_HANDLER,
    [NON_PREFIX_OP_CODES.JMP_RELATIVE_IF_ZERO_FLAG_IS_SET]: JMP_RELATIVE_IF_ZERO_FLAG_IS_SET_HANDLER,
    [NON_PREFIX_OP_CODES.ADD_HL_HL]: ADD_HL_HL_HANDLER,
    [NON_PREFIX_OP_CODES.LOAD_TO_REG_A_VALUE_OF_MEMORY_CELL_FROM_HL_REGISTER_INCREMENT_HL_AFTER]: LOAD_TO_REG_A_VALUE_OF_MEMORY_CELL_FROM_HL_REGISTER_INCREMENT_HL_AFTER_HANDLER,
    [NON_PREFIX_OP_CODES.DEC_HL]: DEC_HL_HANDLER,
    [NON_PREFIX_OP_CODES.INC_L]: INC_L_HANDLER,
    [NON_PREFIX_OP_CODES.DEC_L]: DEC_L_HANDLER,
    [NON_PREFIX_OP_CODES.LOAD_TO_REG_L_VALUE_OF_NEXT_MEMORY_CELL]: LOAD_TO_REG_L_VALUE_OF_NEXT_MEMORY_CELL_HANDLER,
    [NON_PREFIX_OP_CODES.CPL]: CPL_HANDLER,
    [NON_PREFIX_OP_CODES.JMP_RELATIVE_IF_CARRY_FLAG_IS_NOT_SET]: JMP_RELATIVE_IF_CARRY_FLAG_IS_NOT_SET_HANDLER,
    [NON_PREFIX_OP_CODES.LOAD_TO_REG_SP_A_VALUE_OF_NEXT_TWO_MEMORY_CELLS]: LOAD_TO_REG_SP_A_VALUE_OF_NEXT_TWO_MEMORY_CELLS_HANDLER,
    [NON_PREFIX_OP_CODES.LOAD_TO_MEMORY_CELL_FROM_HL_REGISTER_VALUE_OF_A_REGISTER_DECREMENT_HL_AFTER]: LOAD_TO_MEMORY_CELL_FROM_HL_REGISTER_VALUE_OF_A_REGISTER_DECREMENT_HL_AFTER_HANDLER,
    [NON_PREFIX_OP_CODES.INC_SP]: INC_SP_HANDLER,
    [NON_PREFIX_OP_CODES.INC_A_VALUE_OF_MEMORY_CELL_FROM_HL_REGISTER]: INC_A_VALUE_OF_MEMORY_CELL_FROM_HL_REGISTER_HANDLER,
    [NON_PREFIX_OP_CODES.DEC_A_VALUE_OF_MEMORY_CELL_FROM_HL_REGISTER]: DEC_A_VALUE_OF_MEMORY_CELL_FROM_HL_REGISTER_HANDLER,
    [NON_PREFIX_OP_CODES.LOAD_TO_MEMORY_CELL_FROM_HL_REGISTER_VALUE_OF_NEXT_MEMORY_CELL]: LOAD_TO_MEMORY_CELL_FROM_HL_REGISTER_VALUE_OF_NEXT_MEMORY_CELL_HANDLER,
    [NON_PREFIX_OP_CODES.SCF]: SCF_HANDLER,
    [NON_PREFIX_OP_CODES.JMP_RELATIVE_IF_CARRY_FLAG_IS_SET]: JMP_RELATIVE_IF_CARRY_FLAG_IS_SET_HANDLER,
    [NON_PREFIX_OP_CODES.ADD_HL_SP]: ADD_HL_SP_HANDLER,
    [NON_PREFIX_OP_CODES.LOAD_TO_REG_A_VALUE_OF_MEMORY_CELL_FROM_HL_REGISTER_DECREMENT_HL_AFTER]: LOAD_TO_REG_A_VALUE_OF_MEMORY_CELL_FROM_HL_REGISTER_DECREMENT_HL_AFTER_HANDLER,
    [NON_PREFIX_OP_CODES.DEC_SP]: DEC_SP_HANDLER,
    [NON_PREFIX_OP_CODES.INC_A]: INC_A_HANDLER,
    [NON_PREFIX_OP_CODES.DEC_A]: DEC_A_HANDLER,
    [NON_PREFIX_OP_CODES.LOAD_TO_REG_A_VALUE_OF_NEXT_MEMORY_CELL]: LOAD_TO_REG_A_VALUE_OF_NEXT_MEMORY_CELL_HANDLER,
    [NON_PREFIX_OP_CODES.CCF]: CCF_HANDLER,
    [NON_PREFIX_OP_CODES.LOAD_TO_REG_B_VALUE_OF_REG_B]: LOAD_TO_REG_B_VALUE_OF_REG_B_HANDLER,
    [NON_PREFIX_OP_CODES.LOAD_TO_REG_B_VALUE_OF_REG_C]: LOAD_TO_REG_B_VALUE_OF_REG_C_HANDLER,
    [NON_PREFIX_OP_CODES.LOAD_TO_REG_B_VALUE_OF_REG_D]: LOAD_TO_REG_B_VALUE_OF_REG_D_HANDLER,
    [NON_PREFIX_OP_CODES.LOAD_TO_REG_B_VALUE_OF_REG_E]: LOAD_TO_REG_B_VALUE_OF_REG_E_HANDLER,
    [NON_PREFIX_OP_CODES.LOAD_TO_REG_B_VALUE_OF_REG_H]: LOAD_TO_REG_B_VALUE_OF_REG_H_HANDLER,
    [NON_PREFIX_OP_CODES.LOAD_TO_REG_B_VALUE_OF_REG_L]: LOAD_TO_REG_B_VALUE_OF_REG_L_HANDLER,
    [NON_PREFIX_OP_CODES.LOAD_TO_REG_B_VALUE_OF_MEMORY_CELL_FROM_HL_REGISTER]: LOAD_TO_REG_B_VALUE_OF_MEMORY_CELL_FROM_HL_REGISTER_HANDLER,
    [NON_PREFIX_OP_CODES.LOAD_TO_REG_B_VALUE_OF_REG_A]: LOAD_TO_REG_B_VALUE_OF_REG_A_HANDLER,
    [NON_PREFIX_OP_CODES.LOAD_TO_REG_C_VALUE_OF_REG_B]: LOAD_TO_REG_C_VALUE_OF_REG_B_HANDLER,
    [NON_PREFIX_OP_CODES.LOAD_TO_REG_C_VALUE_OF_REG_C]: LOAD_TO_REG_C_VALUE_OF_REG_C_HANDLER,
    [NON_PREFIX_OP_CODES.LOAD_TO_REG_C_VALUE_OF_REG_D]: LOAD_TO_REG_C_VALUE_OF_REG_D_HANDLER,
    [NON_PREFIX_OP_CODES.LOAD_TO_REG_C_VALUE_OF_REG_E]: LOAD_TO_REG_C_VALUE_OF_REG_E_HANDLER,
    [NON_PREFIX_OP_CODES.LOAD_TO_REG_C_VALUE_OF_REG_H]: LOAD_TO_REG_C_VALUE_OF_REG_H_HANDLER,
    [NON_PREFIX_OP_CODES.LOAD_TO_REG_C_VALUE_OF_REG_L]: LOAD_TO_REG_C_VALUE_OF_REG_L_HANDLER,
    [NON_PREFIX_OP_CODES.LOAD_TO_REG_C_VALUE_OF_MEMORY_CELL_FROM_HL_REGISTER]: LOAD_TO_REG_C_VALUE_OF_MEMORY_CELL_FROM_HL_REGISTER_HANDLER,
    [NON_PREFIX_OP_CODES.LOAD_TO_REG_C_VALUE_OF_REG_A]: LOAD_TO_REG_C_VALUE_OF_REG_A_HANDLER,
    [NON_PREFIX_OP_CODES.LOAD_TO_REG_D_VALUE_OF_REG_B]: LOAD_TO_REG_D_VALUE_OF_REG_B_HANDLER,
    [NON_PREFIX_OP_CODES.LOAD_TO_REG_D_VALUE_OF_REG_C]: LOAD_TO_REG_D_VALUE_OF_REG_C_HANDLER,
    [NON_PREFIX_OP_CODES.LOAD_TO_REG_D_VALUE_OF_REG_D]: LOAD_TO_REG_D_VALUE_OF_REG_D_HANDLER,
    [NON_PREFIX_OP_CODES.LOAD_TO_REG_D_VALUE_OF_REG_E]: LOAD_TO_REG_D_VALUE_OF_REG_E_HANDLER,
    [NON_PREFIX_OP_CODES.LOAD_TO_REG_D_VALUE_OF_REG_H]: LOAD_TO_REG_D_VALUE_OF_REG_H_HANDLER,
    [NON_PREFIX_OP_CODES.LOAD_TO_REG_D_VALUE_OF_REG_L]: LOAD_TO_REG_D_VALUE_OF_REG_L_HANDLER,
    [NON_PREFIX_OP_CODES.LOAD_TO_REG_D_VALUE_OF_MEMORY_CELL_FROM_HL_REGISTER]: LOAD_TO_REG_D_VALUE_OF_MEMORY_CELL_FROM_HL_REGISTER_HANDLER,
    [NON_PREFIX_OP_CODES.LOAD_TO_REG_D_VALUE_OF_REG_A]: LOAD_TO_REG_D_VALUE_OF_REG_A_HANDLER,
    [NON_PREFIX_OP_CODES.LOAD_TO_REG_E_VALUE_OF_REG_B]: LOAD_TO_REG_E_VALUE_OF_REG_B_HANDLER,
    [NON_PREFIX_OP_CODES.LOAD_TO_REG_E_VALUE_OF_REG_C]: LOAD_TO_REG_E_VALUE_OF_REG_C_HANDLER,
    [NON_PREFIX_OP_CODES.LOAD_TO_REG_E_VALUE_OF_REG_D]: LOAD_TO_REG_E_VALUE_OF_REG_D_HANDLER,
    [NON_PREFIX_OP_CODES.LOAD_TO_REG_E_VALUE_OF_REG_E]: LOAD_TO_REG_E_VALUE_OF_REG_E_HANDLER,
    [NON_PREFIX_OP_CODES.LOAD_TO_REG_E_VALUE_OF_REG_H]: LOAD_TO_REG_E_VALUE_OF_REG_H_HANDLER,
    [NON_PREFIX_OP_CODES.LOAD_TO_REG_E_VALUE_OF_REG_L]: LOAD_TO_REG_E_VALUE_OF_REG_L_HANDLER,
    [NON_PREFIX_OP_CODES.LOAD_TO_REG_E_VALUE_OF_MEMORY_CELL_FROM_HL_REGISTER]: LOAD_TO_REG_E_VALUE_OF_MEMORY_CELL_FROM_HL_REGISTER_HANDLER,
    [NON_PREFIX_OP_CODES.LOAD_TO_REG_E_VALUE_OF_REG_A]: LOAD_TO_REG_E_VALUE_OF_REG_A_HANDLER,
    [NON_PREFIX_OP_CODES.LOAD_TO_REG_H_VALUE_OF_REG_B]: LOAD_TO_REG_H_VALUE_OF_REG_B_HANDLER,
    [NON_PREFIX_OP_CODES.LOAD_TO_REG_H_VALUE_OF_REG_C]: LOAD_TO_REG_H_VALUE_OF_REG_C_HANDLER,
    [NON_PREFIX_OP_CODES.LOAD_TO_REG_H_VALUE_OF_REG_D]: LOAD_TO_REG_H_VALUE_OF_REG_D_HANDLER,
    [NON_PREFIX_OP_CODES.LOAD_TO_REG_H_VALUE_OF_REG_E]: LOAD_TO_REG_H_VALUE_OF_REG_E_HANDLER,
    [NON_PREFIX_OP_CODES.LOAD_TO_REG_H_VALUE_OF_REG_H]: LOAD_TO_REG_H_VALUE_OF_REG_H_HANDLER,
    [NON_PREFIX_OP_CODES.LOAD_TO_REG_H_VALUE_OF_REG_L]: LOAD_TO_REG_H_VALUE_OF_REG_L_HANDLER,
    [NON_PREFIX_OP_CODES.LOAD_TO_REG_H_VALUE_OF_MEMORY_CELL_FROM_HL_REGISTER]: LOAD_TO_REG_H_VALUE_OF_MEMORY_CELL_FROM_HL_REGISTER_HANDLER,
    [NON_PREFIX_OP_CODES.LOAD_TO_REG_H_VALUE_OF_REG_A]: LOAD_TO_REG_H_VALUE_OF_REG_A_HANDLER,
    [NON_PREFIX_OP_CODES.LOAD_TO_REG_L_VALUE_OF_REG_B]: LOAD_TO_REG_L_VALUE_OF_REG_B_HANDLER,
    [NON_PREFIX_OP_CODES.LOAD_TO_REG_L_VALUE_OF_REG_C]: LOAD_TO_REG_L_VALUE_OF_REG_C_HANDLER,
    [NON_PREFIX_OP_CODES.LOAD_TO_REG_L_VALUE_OF_REG_D]: LOAD_TO_REG_L_VALUE_OF_REG_D_HANDLER,
    [NON_PREFIX_OP_CODES.LOAD_TO_REG_L_VALUE_OF_REG_E]: LOAD_TO_REG_L_VALUE_OF_REG_E_HANDLER,
    [NON_PREFIX_OP_CODES.LOAD_TO_REG_L_VALUE_OF_REG_H]: LOAD_TO_REG_L_VALUE_OF_REG_H_HANDLER,
    [NON_PREFIX_OP_CODES.LOAD_TO_REG_L_VALUE_OF_REG_L]: LOAD_TO_REG_L_VALUE_OF_REG_L_HANDLER,
    [NON_PREFIX_OP_CODES.LOAD_TO_REG_L_VALUE_OF_MEMORY_CELL_FROM_HL_REGISTER]: LOAD_TO_REG_L_VALUE_OF_MEMORY_CELL_FROM_HL_REGISTER_HANDLER,
    [NON_PREFIX_OP_CODES.LOAD_TO_REG_L_VALUE_OF_REG_A]: LOAD_TO_REG_L_VALUE_OF_REG_A_HANDLER,
    [NON_PREFIX_OP_CODES.LOAD_TO_MEMORY_CELL_FROM_HL_REGISTER_VALUE_OF_B_REGISTER]: LOAD_TO_MEMORY_CELL_FROM_HL_REGISTER_VALUE_OF_B_REGISTER_HANDLER,
    [NON_PREFIX_OP_CODES.LOAD_TO_MEMORY_CELL_FROM_HL_REGISTER_VALUE_OF_C_REGISTER]: LOAD_TO_MEMORY_CELL_FROM_HL_REGISTER_VALUE_OF_C_REGISTER_HANDLER,
    [NON_PREFIX_OP_CODES.LOAD_TO_MEMORY_CELL_FROM_HL_REGISTER_VALUE_OF_D_REGISTER]: LOAD_TO_MEMORY_CELL_FROM_HL_REGISTER_VALUE_OF_D_REGISTER_HANDLER,
    [NON_PREFIX_OP_CODES.LOAD_TO_MEMORY_CELL_FROM_HL_REGISTER_VALUE_OF_E_REGISTER]: LOAD_TO_MEMORY_CELL_FROM_HL_REGISTER_VALUE_OF_E_REGISTER_HANDLER,
    [NON_PREFIX_OP_CODES.LOAD_TO_MEMORY_CELL_FROM_HL_REGISTER_VALUE_OF_H_REGISTER]: LOAD_TO_MEMORY_CELL_FROM_HL_REGISTER_VALUE_OF_H_REGISTER_HANDLER,
    [NON_PREFIX_OP_CODES.LOAD_TO_MEMORY_CELL_FROM_HL_REGISTER_VALUE_OF_L_REGISTER]: LOAD_TO_MEMORY_CELL_FROM_HL_REGISTER_VALUE_OF_L_REGISTER_HANDLER,
    [NON_PREFIX_OP_CODES.LOAD_TO_MEMORY_CELL_FROM_HL_REGISTER_VALUE_OF_A_REGISTER]: LOAD_TO_MEMORY_CELL_FROM_HL_REGISTER_VALUE_OF_A_REGISTER_HANDLER,
    [NON_PREFIX_OP_CODES.LOAD_TO_REG_A_VALUE_OF_REG_B]: LOAD_TO_REG_A_VALUE_OF_REG_B_HANDLER,
    [NON_PREFIX_OP_CODES.LOAD_TO_REG_A_VALUE_OF_REG_C]: LOAD_TO_REG_A_VALUE_OF_REG_C_HANDLER,
    [NON_PREFIX_OP_CODES.LOAD_TO_REG_A_VALUE_OF_REG_D]: LOAD_TO_REG_A_VALUE_OF_REG_D_HANDLER,
    [NON_PREFIX_OP_CODES.LOAD_TO_REG_A_VALUE_OF_REG_E]: LOAD_TO_REG_A_VALUE_OF_REG_E_HANDLER,
    [NON_PREFIX_OP_CODES.LOAD_TO_REG_A_VALUE_OF_REG_H]: LOAD_TO_REG_A_VALUE_OF_REG_H_HANDLER,
    [NON_PREFIX_OP_CODES.LOAD_TO_REG_A_VALUE_OF_REG_L]: LOAD_TO_REG_A_VALUE_OF_REG_L_HANDLER,
    [NON_PREFIX_OP_CODES.LOAD_TO_REG_A_VALUE_OF_MEMORY_CELL_FROM_HL_REGISTER]: LOAD_TO_REG_A_VALUE_OF_MEMORY_CELL_FROM_HL_REGISTER_HANDLER,
    [NON_PREFIX_OP_CODES.LOAD_TO_REG_A_VALUE_OF_REG_A]: LOAD_TO_REG_A_VALUE_OF_REG_A_HANDLER,
    [NON_PREFIX_OP_CODES.ADD_TO_REG_A_VALUE_OF_REG_B]: ADD_TO_REG_A_VALUE_OF_REG_B_HANDLER,
    [NON_PREFIX_OP_CODES.ADD_TO_REG_A_VALUE_OF_REG_C]: ADD_TO_REG_A_VALUE_OF_REG_C_HANDLER,
    [NON_PREFIX_OP_CODES.ADD_TO_REG_A_VALUE_OF_REG_D]: ADD_TO_REG_A_VALUE_OF_REG_D_HANDLER,
    [NON_PREFIX_OP_CODES.ADD_TO_REG_A_VALUE_OF_REG_E]: ADD_TO_REG_A_VALUE_OF_REG_E_HANDLER,
    [NON_PREFIX_OP_CODES.ADD_TO_REG_A_VALUE_OF_REG_H]: ADD_TO_REG_A_VALUE_OF_REG_H_HANDLER,
    [NON_PREFIX_OP_CODES.ADD_TO_REG_A_VALUE_OF_REG_L]: ADD_TO_REG_A_VALUE_OF_REG_L_HANDLER,
    [NON_PREFIX_OP_CODES.ADD_TO_REG_A_VALUE_OF_MEMORY_CELL_FROM_HL_REGISTER]: ADD_TO_REG_A_VALUE_OF_MEMORY_CELL_FROM_HL_REGISTER_HANDLER,
    [NON_PREFIX_OP_CODES.ADD_TO_REG_A_VALUE_OF_REG_A]: ADD_TO_REG_A_VALUE_OF_REG_A_HANDLER,
    [NON_PREFIX_OP_CODES.ADC_TO_REG_A_VALUE_OF_REG_B]: ADC_TO_REG_A_VALUE_OF_REG_B_HANDLER,
    [NON_PREFIX_OP_CODES.ADC_TO_REG_A_VALUE_OF_REG_C]: ADC_TO_REG_A_VALUE_OF_REG_C_HANDLER,
    [NON_PREFIX_OP_CODES.ADC_TO_REG_A_VALUE_OF_REG_D]: ADC_TO_REG_A_VALUE_OF_REG_D_HANDLER,
    [NON_PREFIX_OP_CODES.ADC_TO_REG_A_VALUE_OF_REG_E]: ADC_TO_REG_A_VALUE_OF_REG_E_HANDLER,
    [NON_PREFIX_OP_CODES.ADC_TO_REG_A_VALUE_OF_REG_H]: ADC_TO_REG_A_VALUE_OF_REG_H_HANDLER,
    [NON_PREFIX_OP_CODES.ADC_TO_REG_A_VALUE_OF_REG_L]: ADC_TO_REG_A_VALUE_OF_REG_L_HANDLER,
    [NON_PREFIX_OP_CODES.ADC_TO_REG_A_VALUE_OF_MEMORY_CELL_FROM_HL_REGISTER]: ADC_TO_REG_A_VALUE_OF_MEMORY_CELL_FROM_HL_REGISTER_HANDLER,
    [NON_PREFIX_OP_CODES.ADC_TO_REG_A_VALUE_OF_REG_A]: ADC_TO_REG_A_VALUE_OF_REG_A_HANDLER,
    [NON_PREFIX_OP_CODES.SUB_FROM_REG_A_VALUE_OF_REG_B]: SUB_FROM_REG_A_VALUE_OF_REG_B_HANDLER,
    [NON_PREFIX_OP_CODES.SUB_FROM_REG_A_VALUE_OF_REG_C]: SUB_FROM_REG_A_VALUE_OF_REG_C_HANDLER,
    [NON_PREFIX_OP_CODES.SUB_FROM_REG_A_VALUE_OF_REG_D]: SUB_FROM_REG_A_VALUE_OF_REG_D_HANDLER,
    [NON_PREFIX_OP_CODES.SUB_FROM_REG_A_VALUE_OF_REG_E]: SUB_FROM_REG_A_VALUE_OF_REG_E_HANDLER,
    [NON_PREFIX_OP_CODES.SUB_FROM_REG_A_VALUE_OF_REG_H]: SUB_FROM_REG_A_VALUE_OF_REG_H_HANDLER,
    [NON_PREFIX_OP_CODES.SUB_FROM_REG_A_VALUE_OF_REG_L]: SUB_FROM_REG_A_VALUE_OF_REG_L_HANDLER,
    [NON_PREFIX_OP_CODES.SUB_FROM_REG_A_VALUE_OF_MEMORY_CELL_FROM_HL_REGISTER]: SUB_FROM_REG_A_VALUE_OF_MEMORY_CELL_FROM_HL_REGISTER_HANDLER,
    [NON_PREFIX_OP_CODES.SUB_FROM_REG_A_VALUE_OF_REG_A]: SUB_FROM_REG_A_VALUE_OF_REG_A_HANDLER,
    [NON_PREFIX_OP_CODES.SBC_FROM_REG_A_VALUE_OF_REG_B]: SBC_FROM_REG_A_VALUE_OF_REG_B_HANDLER,
    [NON_PREFIX_OP_CODES.SBC_FROM_REG_A_VALUE_OF_REG_C]: SBC_FROM_REG_A_VALUE_OF_REG_C_HANDLER,
    [NON_PREFIX_OP_CODES.SBC_FROM_REG_A_VALUE_OF_REG_D]: SBC_FROM_REG_A_VALUE_OF_REG_D_HANDLER,
    [NON_PREFIX_OP_CODES.SBC_FROM_REG_A_VALUE_OF_REG_E]: SBC_FROM_REG_A_VALUE_OF_REG_E_HANDLER,
    [NON_PREFIX_OP_CODES.SBC_FROM_REG_A_VALUE_OF_REG_H]: SBC_FROM_REG_A_VALUE_OF_REG_H_HANDLER,
    [NON_PREFIX_OP_CODES.SBC_FROM_REG_A_VALUE_OF_REG_L]: SBC_FROM_REG_A_VALUE_OF_REG_L_HANDLER,
    [NON_PREFIX_OP_CODES.SBC_FROM_REG_A_VALUE_OF_MEMORY_CELL_FROM_HL_REGISTER]: SBC_FROM_REG_A_VALUE_OF_MEMORY_CELL_FROM_HL_REGISTER_HANDLER,
    [NON_PREFIX_OP_CODES.SBC_FROM_REG_A_VALUE_OF_REG_A]: SBC_FROM_REG_A_VALUE_OF_REG_A_HANDLER,
    [NON_PREFIX_OP_CODES.AND_B]: AND_B_HANDLER,
    [NON_PREFIX_OP_CODES.AND_C]: AND_C_HANDLER,
    [NON_PREFIX_OP_CODES.AND_D]: AND_D_HANDLER,
    [NON_PREFIX_OP_CODES.AND_E]: AND_E_HANDLER,
    [NON_PREFIX_OP_CODES.AND_H]: AND_H_HANDLER,
    [NON_PREFIX_OP_CODES.AND_L]: AND_L_HANDLER,
    [NON_PREFIX_OP_CODES.AND_A_VALUE_OF_MEMORY_CELL_FROM_HL_REGISTER]: AND_A_VALUE_OF_MEMORY_CELL_FROM_HL_REGISTER_HANDLER,
    [NON_PREFIX_OP_CODES.AND_A]: AND_A_HANDLER,
    [NON_PREFIX_OP_CODES.XOR_B]: XOR_B_HANDLER,
    [NON_PREFIX_OP_CODES.XOR_C]: XOR_C_HANDLER,
    [NON_PREFIX_OP_CODES.XOR_D]: XOR_D_HANDLER,
    [NON_PREFIX_OP_CODES.XOR_E]: XOR_E_HANDLER,
    [NON_PREFIX_OP_CODES.XOR_H]: XOR_H_HANDLER,
    [NON_PREFIX_OP_CODES.XOR_L]: XOR_L_HANDLER,
    [NON_PREFIX_OP_CODES.XOR_A_VALUE_OF_MEMORY_CELL_FROM_HL_REGISTER]: XOR_A_VALUE_OF_MEMORY_CELL_FROM_HL_REGISTER_HANDLER,
    [NON_PREFIX_OP_CODES.XOR_A]: XOR_A_HANDLER,
    [NON_PREFIX_OP_CODES.OR_B]: OR_B_HANDLER,
    [NON_PREFIX_OP_CODES.OR_C]: OR_C_HANDLER,
    [NON_PREFIX_OP_CODES.OR_D]: OR_D_HANDLER,
    [NON_PREFIX_OP_CODES.OR_E]: OR_E_HANDLER,
    [NON_PREFIX_OP_CODES.OR_H]: OR_H_HANDLER,
    [NON_PREFIX_OP_CODES.OR_L]: OR_L_HANDLER,
    [NON_PREFIX_OP_CODES.OR_A_VALUE_OF_MEMORY_CELL_FROM_HL_REGISTER]: OR_A_VALUE_OF_MEMORY_CELL_FROM_HL_REGISTER_HANDLER,
    [NON_PREFIX_OP_CODES.OR_A]: OR_A_HANDLER,
    [NON_PREFIX_OP_CODES.CP_B]: CP_B_HANDLER,
    [NON_PREFIX_OP_CODES.CP_C]: CP_C_HANDLER,
    [NON_PREFIX_OP_CODES.CP_D]: CP_D_HANDLER,
    [NON_PREFIX_OP_CODES.CP_E]: CP_E_HANDLER,
    [NON_PREFIX_OP_CODES.CP_H]: CP_H_HANDLER,
    [NON_PREFIX_OP_CODES.CP_L]: CP_L_HANDLER,
    [NON_PREFIX_OP_CODES.CP_A_VALUE_OF_MEMORY_CELL_FROM_HL_REGISTER]: CP_A_VALUE_OF_MEMORY_CELL_FROM_HL_REGISTER_HANDLER,
    [NON_PREFIX_OP_CODES.CP_A]: CP_A_HANDLER,
    [NON_PREFIX_OP_CODES.RETURN_IF_ZERO_FLAG_IS_NOT_SET]: RETURN_IF_ZERO_FLAG_IS_NOT_SET_HANDLER,
    [NON_PREFIX_OP_CODES.POP_BC]: POP_BC_HANDLER,
    [NON_PREFIX_OP_CODES.JMP_IF_ZERO_FLAG_IS_NOT_SET]: JMP_IF_ZERO_FLAG_IS_NOT_SET_HANDLER,
    [NON_PREFIX_OP_CODES.JMP]: JMP_HANDLER,
    [NON_PREFIX_OP_CODES.CALL_IF_ZERO_FLAG_IS_NOT_SET]: CALL_IF_ZERO_FLAG_IS_NOT_SET_HANDLER,
    [NON_PREFIX_OP_CODES.PUSH_BC]: PUSH_BC_HANDLER,
    [NON_PREFIX_OP_CODES.ADD_TO_REG_A_VALUE_FROM_NEXT_MEMORY_CELL]: ADD_TO_REG_A_VALUE_FROM_NEXT_MEMORY_CELL_HANDLER,
    [NON_PREFIX_OP_CODES.RST_0]: RST_0_HANDLER,
    [NON_PREFIX_OP_CODES.RETURN_IF_ZERO_FLAG_IS_SET]: RETURN_IF_ZERO_FLAG_IS_SET_HANDLER,
    [NON_PREFIX_OP_CODES.RETURN]: RETURN_HANDLER,
    [NON_PREFIX_OP_CODES.JMP_IF_ZERO_FLAG_IS_SET]: JMP_IF_ZERO_FLAG_IS_SET_HANDLER,
    [NON_PREFIX_OP_CODES.CALL_IF_ZERO_FLAG_IS_SET]: CALL_IF_ZERO_FLAG_IS_SET_HANDLER,
    [NON_PREFIX_OP_CODES.CALL]: CALL_HANDLER,
    [NON_PREFIX_OP_CODES.ADC_TO_REG_A_VALUE_FROM_NEXT_MEMORY_CELL]: ADC_TO_REG_A_VALUE_FROM_NEXT_MEMORY_CELL_HANDLER,
    [NON_PREFIX_OP_CODES.RST_08]: RST_08_HANDLER,
    [NON_PREFIX_OP_CODES.RETURN_IF_CARRY_FLAG_IS_NOT_SET]: RETURN_IF_CARRY_FLAG_IS_NOT_SET_HANDLER,
    [NON_PREFIX_OP_CODES.POP_DE]: POP_DE_HANDLER,
    [NON_PREFIX_OP_CODES.JMP_IF_CARRY_FLAG_IS_NOT_SET]: JMP_IF_CARRY_FLAG_IS_NOT_SET_HANDLER,
    [NON_PREFIX_OP_CODES.CALL_IF_CARRY_FLAG_IS_NOT_SET]: CALL_IF_CARRY_FLAG_IS_NOT_SET_HANDLER,
    [NON_PREFIX_OP_CODES.PUSH_DE]: PUSH_DE_HANDLER,
    [NON_PREFIX_OP_CODES.SUB_FROM_REG_A_VALUE_FROM_NEXT_MEMORY_CELL]: SUB_FROM_REG_A_VALUE_FROM_NEXT_MEMORY_CELL_HANDLER,
    [NON_PREFIX_OP_CODES.RST_10]: RST_10_HANDLER,
    [NON_PREFIX_OP_CODES.RETURN_IF_CARRY_FLAG_IS_SET]: RETURN_IF_CARRY_FLAG_IS_SET_HANDLER,
    [NON_PREFIX_OP_CODES.RETURN_AND_ENABLE_INTERRUPTS]: RETURN_AND_ENABLE_INTERRUPTS_HANDLER,
    [NON_PREFIX_OP_CODES.JMP_IF_CARRY_FLAG_IS_SET]: JMP_IF_CARRY_FLAG_IS_SET_HANDLER,
    [NON_PREFIX_OP_CODES.CALL_IF_CARRY_IS_SET]: CALL_IF_CARRY_IS_SET_HANDLER,
    [NON_PREFIX_OP_CODES.SBC_FROM_REG_A_VALUE_FROM_NEXT_MEMORY_CELL]: SBC_FROM_REG_A_VALUE_FROM_NEXT_MEMORY_CELL_HANDLER,
    [NON_PREFIX_OP_CODES.RST_18]: RST_18_HANDLER,
    [NON_PREFIX_OP_CODES.LOAD_HIGH_TO_MEMORY_CELL_COMBINED_FROM_NEXT_MEMORY_CELL_VALUE_OF_A_REGISTER]: LOAD_HIGH_TO_MEMORY_CELL_COMBINED_FROM_NEXT_MEMORY_CELL_VALUE_OF_A_REGISTER_HANDLER,
    [NON_PREFIX_OP_CODES.POP_HL]: POP_HL_HANDLER,
    [NON_PREFIX_OP_CODES.LOAD_TO_MEMORY_CELL_FROM_C_REGISTER_VALUE_OF_A_REGISTER]: LOAD_TO_MEMORY_CELL_FROM_C_REGISTER_VALUE_OF_A_REGISTER_HANDLER,
    [NON_PREFIX_OP_CODES.PUSH_HL]: PUSH_HL_HANDLER,
    [NON_PREFIX_OP_CODES.AND_A_VALUE_FROM_NEXT_MEMORY_CELL]: AND_A_VALUE_FROM_NEXT_MEMORY_CELL_HANDLER,
    [NON_PREFIX_OP_CODES.RST_20]: RST_20_HANDLER,
    [NON_PREFIX_OP_CODES.ADD_TO_SP_A_VALUE_FROM_NEXT_MEMORY_CELL]: ADD_TO_SP_A_VALUE_FROM_NEXT_MEMORY_CELL_HANDLER,
    [NON_PREFIX_OP_CODES.JMP_TO_HL]: JMP_TO_HL_HANDLER,
    [NON_PREFIX_OP_CODES.LOAD_TO_MEMORY_CELL_COMBINED_FROM_TWO_NEXT_MEMORY_CELL_VALUE_OF_A_REGISTER]: LOAD_TO_MEMORY_CELL_COMBINED_FROM_TWO_NEXT_MEMORY_CELL_VALUE_OF_A_REGISTER_HANDLER,
    [NON_PREFIX_OP_CODES.XOR_A_VALUE_FROM_NEXT_MEMORY_CELL]: XOR_A_VALUE_FROM_NEXT_MEMORY_CELL_HANDLER,
    [NON_PREFIX_OP_CODES.RST_28]: RST_28_HANDLER
};

export default JUMP_TABLE;