const PROGRAM_NAME_START_INDEX = 0x134;
const PROGRAM_NAME_END_INDEX = 0x13F;
const PROGRAM_MANUFACTURER_CODE_START_INDEX = 0x13F;
const PROGRAM_MANUFACTURER_CODE_END_INDEX = 0x143;
const GBC_FLAG_INDEX = 0x143;
const SGB_FLAG_INDEX = 0x146;
const OLD_LICENSE_CODE_INDEX = 0x14B;
const NEW_LICENSE_FLAG_VALUE = 0x33;
const NEW_LICENSE_START_INDEX = 0x144;
const NEW_LICENSE_END_INDEX = 0x145;
const CARTRIDGE_TYPE_INDEX = 0x147;
const ROM_SIZE_INDEX = 0x148;
const RAM_SIZE_INDEX = 0x149;
const DESTINATION_CODE_INDEX = 0x14A;

export {
    PROGRAM_NAME_START_INDEX,
    PROGRAM_NAME_END_INDEX,
    PROGRAM_MANUFACTURER_CODE_START_INDEX,
    PROGRAM_MANUFACTURER_CODE_END_INDEX,
    GBC_FLAG_INDEX,
    SGB_FLAG_INDEX,
    OLD_LICENSE_CODE_INDEX,
    NEW_LICENSE_FLAG_VALUE,
    NEW_LICENSE_START_INDEX,
    NEW_LICENSE_END_INDEX,
    CARTRIDGE_TYPE_INDEX,
    ROM_SIZE_INDEX,
    RAM_SIZE_INDEX,
    DESTINATION_CODE_INDEX
}