export enum REGULAR_OP_CODES {
    LOAD_TO_REG_A_VALUE_OF_REG_A = 0x7F,
    LOAD_TO_REG_A_VALUE_OF_REG_B = 0x78,
    LOAD_TO_REG_A_VALUE_OF_REG_C = 0x79,
    LOAD_TO_REG_A_VALUE_OF_REG_D = 0x7A,
    LOAD_TO_REG_A_VALUE_OF_REG_E = 0x7B,
    LOAD_TO_REG_A_VALUE_OF_REG_H = 0x7C,
    LOAD_TO_REG_A_VALUE_OF_REG_L = 0x7D

}

export enum CB_OP_CODES {

}