export enum REGULAR_OP_CODES {
    LOAD_TO_REG_A_VALUE_OF_REG_A = 0x7F,
    LOAD_TO_REG_A_VALUE_OF_REG_B = 0x78,
    LOAD_TO_REG_A_VALUE_OF_REG_C = 0x79,
    LOAD_TO_REG_A_VALUE_OF_REG_D = 0x7A,
    LOAD_TO_REG_A_VALUE_OF_REG_E = 0x7B,
    LOAD_TO_REG_A_VALUE_OF_REG_H = 0x7C,
    LOAD_TO_REG_A_VALUE_OF_REG_L = 0x7D,

    LOAD_TO_REG_B_VALUE_OF_REG_A = 0x47,
    LOAD_TO_REG_B_VALUE_OF_REG_B = 0x40,
    LOAD_TO_REG_B_VALUE_OF_REG_C = 0x41,
    LOAD_TO_REG_B_VALUE_OF_REG_D = 0x42,
    LOAD_TO_REG_B_VALUE_OF_REG_E = 0x43,
    LOAD_TO_REG_B_VALUE_OF_REG_H = 0x44,
    LOAD_TO_REG_B_VALUE_OF_REG_L = 0x45,

    LOAD_TO_REG_C_VALUE_OF_REG_A = 0x4F,
    LOAD_TO_REG_C_VALUE_OF_REG_B = 0x48,
    LOAD_TO_REG_C_VALUE_OF_REG_C = 0x49,
    LOAD_TO_REG_C_VALUE_OF_REG_D = 0x4A,
    LOAD_TO_REG_C_VALUE_OF_REG_E = 0x4B,
    LOAD_TO_REG_C_VALUE_OF_REG_H = 0x4C,
    LOAD_TO_REG_C_VALUE_OF_REG_L = 0x4D,

    LOAD_TO_REG_D_VALUE_OF_REG_A = 0x57,
    LOAD_TO_REG_D_VALUE_OF_REG_B = 0x50,
    LOAD_TO_REG_D_VALUE_OF_REG_C = 0x51,
    LOAD_TO_REG_D_VALUE_OF_REG_D = 0x52,
    LOAD_TO_REG_D_VALUE_OF_REG_E = 0x53,
    LOAD_TO_REG_D_VALUE_OF_REG_H = 0x54,
    LOAD_TO_REG_D_VALUE_OF_REG_L = 0x55,
}

export enum CB_OP_CODES {

}