import EVENT_TYPES from "./events/types";
import { UNMAP_BIOS_EVENT, UNMAP_BIOS_EVENT_HANDLER } from "./events/UNMAP_BIOS";
import { REDRAW_SPRITE_EVENT, REDRAW_SPRITE_EVENT_HANDLER } from "./events/REDRAW_SPRITE";
import { REQUEST_TIMA_INTERRUPT_EVENT, REQUEST_TIMA_INTERRUPT_EVENT_HANDLER } from "./events/REQUEST_TIMA_INTERRUPT";
import { REQUEST_LCD_INTERRUPT_EVENT, REQUEST_LCD_INTERRUPT_EVENT_HANDLER } from "./events/REQUEST_LCD_INERRUPT";
import { REQUEST_VBLANK_INTERRUPT_EVENT, REQUEST_VBLANK_INTERRUPT_EVENT_HANDLER } from "./events/REQUEST_VBLANK_INTERRUPT";

type EVENT_HANDLERS = UNMAP_BIOS_EVENT_HANDLER | REDRAW_SPRITE_EVENT_HANDLER | REQUEST_TIMA_INTERRUPT_EVENT_HANDLER | REQUEST_LCD_INTERRUPT_EVENT_HANDLER | REQUEST_VBLANK_INTERRUPT_EVENT_HANDLER;
type EVENTS = UNMAP_BIOS_EVENT | REDRAW_SPRITE_EVENT | REQUEST_TIMA_INTERRUPT_EVENT | REQUEST_LCD_INTERRUPT_EVENT | REQUEST_VBLANK_INTERRUPT_EVENT;
type CALLBACK = (data: any) => void

interface IBusEventHandlers {
    [index: string]: CALLBACK[]
}


export {
    EVENT_TYPES,
    IBusEventHandlers,
    EVENTS,
    EVENT_HANDLERS
};