enum EVENT_TYPES {
    "UNAMP_BIOS",
    "REDRAW_SPRITE",
    "REQUEST_TIMA_INTERRUPT",
    "REQUEST_LCD_INTERRUPT",
    "REQUEST_VBLANK_INTERRUPT",
    "REQUEST_JOYPAD_INTERRUPT"
}

export default EVENT_TYPES;