import EVENT_TYPES from "../types";

interface REQUEST_JOYPAD_INTERRUPT_EVENT_DATA {};

interface REQUEST_JOYPAD_INTERRUPT_EVENT {
    type: EVENT_TYPES.REQUEST_JOYPAD_INTERRUPT,
    data: REQUEST_JOYPAD_INTERRUPT_EVENT_DATA
}

interface REQUEST_JOYPAD_INTERRUPT_EVENT_HANDLER {
    type: EVENT_TYPES.REQUEST_JOYPAD_INTERRUPT,
    callback: (data: REQUEST_JOYPAD_INTERRUPT_EVENT_DATA) => void
}

class RequestJoypadInterruptEvent implements REQUEST_JOYPAD_INTERRUPT_EVENT {
    type: number = EVENT_TYPES.REQUEST_JOYPAD_INTERRUPT;
    data = {};
}

export {
    REQUEST_JOYPAD_INTERRUPT_EVENT,
    REQUEST_JOYPAD_INTERRUPT_EVENT_DATA,
    REQUEST_JOYPAD_INTERRUPT_EVENT_HANDLER,
    RequestJoypadInterruptEvent
}